// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfyxmrskfmzufjqaanjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmeXhtcnNrZm16dWZqcWFhbmpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTk5NDYsImV4cCI6MjA1OTI3NTk0Nn0.zH9NeCum5PmH9ZTmsOHZVTVFk7rdn4s8_QiBrIYSCVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});